import { siteConfig } from "@/lib/site";

export const LEGAL_LAST_UPDATED = "2026-07-14";

export type LegalLink = {
  label: string;
  href: string;
};

export type LegalSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  /** Optional external references (e.g. third-party provider privacy policies). */
  links?: LegalLink[];
};

export type LegalDocument = {
  title: string;
  description: string;
  sections: LegalSection[];
};

export const termsOfService: LegalDocument = {
  title: "Terms of Service",
  description:
    "The terms that govern access to and use of MindPAL, including clear disclosures about AI-generated content and third-party AI processing.",
  sections: [
    {
      title: "Introduction",
      paragraphs: [
        `These Terms of Service ("Terms") govern your access to and use of ${siteConfig.name}, operated by PAL ("we", "us", or "our"). By using ${siteConfig.name}, you agree to these Terms.`,
        `These Terms also serve as the End User License Agreement (EULA) for the ${siteConfig.name} mobile app. For subscriptions and purchases made through the Apple App Store, Apple's Standard End User License Agreement also applies; to the extent it conflicts with these Terms for App Store users, the Apple Standard EULA governs your license to use the app.`,
      ],
    },
    {
      title: "Acceptance of Terms",
      paragraphs: [
        `You must read and accept these Terms before using ${siteConfig.name}. If you do not agree, do not use the app or website.`,
      ],
    },
    {
      title: `What ${siteConfig.name} Is`,
      paragraphs: [
        `${siteConfig.name} is an AI-powered emotional support and wellbeing companion. It offers reflective conversation, journaling-style guidance, mood support, and optional voice interaction.`,
      ],
    },
    {
      title: `What ${siteConfig.name} Is Not`,
      paragraphs: [
        `${siteConfig.name} is not a medical device, therapist, psychologist, psychiatrist, counselor, or emergency service. It does not provide diagnosis, treatment, prescriptions, clinical advice, or crisis intervention.`,
      ],
    },
    {
      title: "Not for Emergencies",
      paragraphs: [
        `Do not use ${siteConfig.name} if you are in immediate danger or may harm yourself or others. Contact local emergency services or a trusted person immediately.`,
      ],
    },
    {
      title: "AI-Generated Content Disclaimer",
      paragraphs: [
        "Responses are generated by artificial intelligence and may be inaccurate, incomplete, inappropriate, or unsuitable for your situation. You are responsible for how you use AI-generated content.",
      ],
    },
    {
      title: "AI Processing and User Messages",
      paragraphs: [
        "When you send messages, reflections, check-ins, prompts, uploaded or attached content, or voice transcripts, that content and limited context from the conversation may be sent to third-party AI services — Anthropic for text and safety AI, and ElevenLabs for voice — to generate responses, provide wellbeing features, maintain safety, and prevent abuse.",
        "Before this data is shared, the app discloses what is sent, names Anthropic and ElevenLabs, and asks for your explicit permission. Do not submit information you do not want processed by these providers. AI providers process the content under their own policies and our agreements, are required to protect it to a standard equal to our Privacy Policy, and may retain limited data where required for security, abuse prevention, or legal compliance.",
      ],
    },
    {
      title: "User Responsibilities",
      bullets: [
        "Provide accurate account information where required.",
        "Use the service lawfully and respectfully.",
        "Seek professional help for serious mental health or medical concerns.",
        "Do not rely on AI for critical medical, safety, legal, financial, or emergency decisions.",
      ],
    },
    {
      title: "Subscriptions, Billing, Free Trials, and Cancellations",
      paragraphs: [
        "MindPAL offers MindPAL Plus, an auto-renewable monthly subscription that unlocks expanded messaging, included premium voice minutes, and Plus-only features. The price is shown in the app on the subscription screen before purchase (for example, US$9.99/month; prices are localized and confirmed at checkout by your app store).",
        "MindPAL also offers optional one-time (consumable) purchases such as additional voice minutes and Chat Token packs. These are charged once and do not auto-renew.",
        "Payment is charged to your app store account at confirmation of purchase. An auto-renewable subscription renews for the same period and price unless it is turned off at least 24 hours before the end of the current period. You can manage or cancel a subscription anytime in your app store account settings; deleting the app does not cancel a subscription. Any unused portion of a free trial, if offered, is forfeited when you purchase a subscription.",
      ],
    },
    {
      title: "Voice Features",
      paragraphs: [
        "Voice features may receive user audio, convert it to text, and generate audio responses. This processing may be performed by ElevenLabs and Anthropic. For more details on processing, retention, and consent, see our Privacy Policy and in-app voice consent notice.",
      ],
    },
    {
      title: "Privacy and Data",
      paragraphs: [
        "Our Privacy Policy explains what information we collect, how we use it, what data may be sent to third-party AI providers, and how you can exercise your privacy rights.",
      ],
    },
    {
      title: "Third-Party Services",
      paragraphs: [
        "We use third-party providers including Anthropic (chat and safety AI), ElevenLabs (voice), Firebase Analytics, app stores, payment processors, and infrastructure providers. Their handling of data is described in our Privacy Policy, and AI providers are required to protect your data to a standard equal to ours.",
      ],
      links: [
        { label: "Anthropic Privacy Policy", href: "https://www.anthropic.com/legal/privacy" },
        { label: "ElevenLabs Privacy Policy", href: "https://elevenlabs.io/privacy" },
      ],
    },
    {
      title: "Availability and Changes to the Service",
      paragraphs: [
        "We may modify, suspend, or discontinue features with reasonable notice where practicable.",
      ],
    },
    {
      title: "Intellectual Property",
      paragraphs: [
        `${siteConfig.name} content, branding, and software are owned by PAL or its licensors. You receive a limited, non-exclusive license to use the service for personal, non-commercial purposes.`,
      ],
    },
    {
      title: "Termination",
      paragraphs: [
        "We may suspend or terminate access for violations of these Terms or to protect users and the service. You may stop using the app at any time and delete your account in Settings.",
      ],
    },
    {
      title: "Disclaimers and Limitation of Liability",
      paragraphs: [
        'The service is provided "as is" and "as available" without warranties of any kind. To the maximum extent permitted by law, PAL shall not be liable for indirect, incidental, special, consequential, or punitive damages, or any loss arising from your use of or reliance on AI-generated content.',
      ],
    },
    {
      title: "Governing Law",
      paragraphs: [
        "These Terms are governed by the laws of the State of Georgia, United States, without regard to conflict-of-law principles.",
      ],
    },
    {
      title: "Changes to Terms",
      paragraphs: [
        'We may update these Terms. Material changes will be communicated in-app or by other reasonable means. Continued use after the effective date or updated "Last updated" date constitutes acceptance.',
      ],
    },
    {
      title: "Contact Information",
      paragraphs: [
        `Questions and support requests: ${siteConfig.supportEmail}. PAL, Georgia, United States.`,
      ],
    },
  ],
};

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  description:
    "How MindPAL collects, uses, shares, and protects your information, including what is sent to third-party AI services to generate responses.",
  sections: [
    {
      title: "Introduction",
      paragraphs: [
        `This Privacy Policy describes how PAL collects, uses, shares, and protects information when you use ${siteConfig.name}.`,
      ],
    },
    {
      title: "Information We Collect",
      paragraphs: [
        "We collect information you provide and information generated through your use of the app and website, as described below.",
      ],
    },
    {
      title: "Account Information",
      bullets: [
        "Email address and authentication identifiers.",
        "Profile, subscription status, and app entitlements.",
        "Account preferences, language, and support communications.",
      ],
    },
    {
      title: "Conversation, Journal, and User-Provided Content",
      paragraphs: [
        "We collect the text you enter, AI responses, journal-style reflections, check-ins, saved memories, uploaded or attached content where supported, and related metadata. This content may include sensitive personal information if you choose to provide it.",
      ],
    },
    {
      title: "Voice Data and Transcripts",
      paragraphs: [
        "If you use voice features, audio may be processed temporarily to convert speech to text and generate audio replies. We do not store raw audio recordings; voice input is processed in real time and deleted after processing. Transcripts and related context may be processed and stored according to this Privacy Policy.",
      ],
    },
    {
      title: "Mood, Wellbeing, Usage, Device, and Technical Data",
      bullets: [
        "Mood check-ins, feature usage, session metrics, and plan limit information.",
        "Device type, operating system version, app version, language, locale, crash logs, and performance logs.",
        "Purchase records and subscription status from app stores. We do not store full payment card numbers.",
      ],
    },
    {
      title: "How We Use Information",
      bullets: [
        "Provide, personalize, and improve emotional support, reflection, and voice features.",
        "Authenticate users, sync data where enabled, and enforce plan limits.",
        "Process AI and voice requests and generate AI responses.",
        "Maintain safety, detect abuse, troubleshoot issues, and comply with law.",
        "Communicate with you about the service, support, and important updates.",
      ],
    },
    {
      title: "Data Sent to Third-Party AI Services",
      paragraphs: [
        "MindPAL relies on third-party AI providers to generate responses and operate its features. When you use chat and other text features, the following may be sent to Anthropic (the provider of the Claude AI models): the messages or journal text you submit, relevant conversation context, optional photos you attach, reflections and check-in content, AI safety signals, and limited technical request metadata needed to operate the service.",
        "When you use voice features, your audio is sent to ElevenLabs for speech-to-text and voice generation, and the resulting transcript and relevant context are then sent to Anthropic to generate PAL's reply. We do not store raw audio recordings; voice input is processed in real time and deleted after processing.",
        "We use this processing only to provide MindPAL's AI conversation, reflection, safety, voice, and support features. We do not sell your personal information and do not use your private conversations for advertising or to train third-party foundation models.",
      ],
    },
    {
      title: "Third-Party AI Providers and Equivalent Protection",
      paragraphs: [
        "We only work with reputable AI providers that maintain industry-standard security and privacy practices. Our providers are Anthropic (chat, reflection, and safety AI) and ElevenLabs (speech-to-text and voice generation for voice features).",
        "These providers act as our service providers / processors. They are bound by contract (or equivalent terms) to process the personal data we send only to provide their services to us, to keep it secure, and not to sell it or use it for their own advertising. We require them to provide privacy and security protections that are the same as, or equal to, those described in this Privacy Policy for the data they process on our behalf, subject to their published policies and applicable law.",
        "You can review each provider's own privacy practices directly:",
      ],
      links: [
        { label: "Anthropic Privacy Policy", href: "https://www.anthropic.com/legal/privacy" },
        { label: "ElevenLabs Privacy Policy", href: "https://elevenlabs.io/privacy" },
      ],
    },
    {
      title: "Your In-App Consent Before AI Sharing",
      paragraphs: [
        "Before any messages, conversation context, attachments, or voice data are sent to Anthropic or ElevenLabs, the MindPAL app shows an in-app disclosure that names these providers and explains what is sent and why, and asks for your explicit permission. Accepting this Privacy Policy is not the only control — you also see and must accept a dedicated AI data-sharing consent screen inside the app, and a separate voice consent notice before any audio is sent.",
        "If you decline, features that require third-party AI processing are not available, but you can continue to use parts of the app that do not require it. You can review these disclosures again in the app under Settings → Legal → AI Disclosure and Privacy Policy.",
      ],
    },
    {
      title: "How We Share Information",
      paragraphs: [
        "We share information with service providers who help us operate the app and website, including AI providers (Anthropic), voice providers (ElevenLabs), infrastructure and hosting providers, analytics providers, app stores, payment processors, and customer support tools. Each is permitted to use the data only to provide services to us and must protect it to a standard equal to this policy. We may also disclose information when required by law, to protect rights and safety, or in connection with a business transfer.",
        "We do not sell your personal information and do not share private conversations for cross-context behavioral advertising.",
      ],
    },
    {
      title: "Data Retention and Deletion",
      paragraphs: [
        "We retain personal data for up to 365 days after your last activity with the service, or for as long as necessary to provide the service, comply with legal obligations, resolve disputes, and enforce our agreements. You may delete conversations and your account using in-app controls or by contacting support.",
      ],
    },
    {
      title: "Security",
      paragraphs: [
        "We use industry-standard safeguards. Data is encrypted in transit using TLS (HTTPS), and saved conversations and memories are encrypted at rest. No method of transmission or storage is completely secure, but we work to protect your data at every layer.",
      ],
    },
    {
      title: "International Data Transfers",
      paragraphs: [
        "Your information may be processed in countries other than your own, with appropriate safeguards where required.",
      ],
    },
    {
      title: "Children and Minors",
      paragraphs: [
        `${siteConfig.name} is not intended for children under 13 or the minimum age required in your region. We do not knowingly collect personal information from children without appropriate consent.`,
      ],
    },
    {
      title: "Your Rights",
      bullets: [
        "Access, correction, deletion, and portability where applicable.",
        "Withdraw consent for optional processing, including optional voice features.",
        "Object to or restrict certain processing where the law provides that right.",
        "Lodge a complaint with a supervisory authority where applicable.",
      ],
    },
    {
      title: "California / CCPA Notice",
      paragraphs: [
        "California residents may have additional rights regarding access, deletion, correction, opt-out of certain sharing, and limitation of sensitive personal information. We do not sell personal information or share it for cross-context behavioral advertising.",
      ],
    },
    {
      title: "GDPR Notice",
      paragraphs: [
        `EEA/UK users may contact ${siteConfig.supportEmail} for GDPR-related requests. Where applicable, we rely on contract performance, legitimate interests, consent, and legal obligations as our legal bases for processing.`,
      ],
    },
    {
      title: "Changes to Privacy Policy",
      paragraphs: [
        'We may update this Privacy Policy. The "Last updated" date will change and material updates will be communicated in-app or by other reasonable means where appropriate.',
      ],
    },
    {
      title: "Contact Information",
      paragraphs: [`Privacy and support requests: ${siteConfig.supportEmail}.`],
    },
  ],
};
