import { siteConfig } from "@/lib/site";

export const LEGAL_LAST_UPDATED = "2026-07-07";

export type LegalSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type LegalDocument = {
  title: string;
  description: string;
  sections: LegalSection[];
};

export const termsOfService: LegalDocument = {
  title: "Terms of Service",
  description:
    "The terms that govern access to and use of MindPAL, including clear disclosures about AI-generated content and third-party AI processing.",
  sections: [
    {
      title: "Introduction",
      paragraphs: [
        `These Terms of Service ("Terms") govern your access to and use of ${siteConfig.name}, operated by PAL ("we", "us", or "our"). By using ${siteConfig.name}, you agree to these Terms.`,
      ],
    },
    {
      title: "Acceptance of Terms",
      paragraphs: [
        `You must read and accept these Terms before using ${siteConfig.name}. If you do not agree, do not use the app or website.`,
      ],
    },
    {
      title: `What ${siteConfig.name} Is`,
      paragraphs: [
        `${siteConfig.name} is an AI-powered emotional support and wellbeing companion. It offers reflective conversation, journaling-style guidance, mood support, and optional voice interaction.`,
      ],
    },
    {
      title: `What ${siteConfig.name} Is Not`,
      paragraphs: [
        `${siteConfig.name} is not a medical device, therapist, psychologist, psychiatrist, counselor, or emergency service. It does not provide diagnosis, treatment, prescriptions, clinical advice, or crisis intervention.`,
      ],
    },
    {
      title: "Not for Emergencies",
      paragraphs: [
        `Do not use ${siteConfig.name} if you are in immediate danger or may harm yourself or others. Contact local emergency services or a trusted person immediately.`,
      ],
    },
    {
      title: "AI-Generated Content Disclaimer",
      paragraphs: [
        "Responses are generated by artificial intelligence and may be inaccurate, incomplete, inappropriate, or unsuitable for your situation. You are responsible for how you use AI-generated content.",
      ],
    },
    {
      title: "AI Processing and User Messages",
      paragraphs: [
        "When you send messages, reflections, check-ins, prompts, uploaded or attached content, or voice transcripts, that content and limited context from the conversation may be sent to third-party AI services, including Anthropic, to generate responses, provide wellbeing features, maintain safety, and prevent abuse.",
        "Do not submit information you do not want processed by these providers. AI providers process the content under their own policies and our agreements; they may retain limited data where required for security, abuse prevention, or legal compliance.",
      ],
    },
    {
      title: "User Responsibilities",
      bullets: [
        "Provide accurate account information where required.",
        "Use the service lawfully and respectfully.",
        "Seek professional help for serious mental health or medical concerns.",
        "Do not rely on AI for critical medical, safety, legal, financial, or emergency decisions.",
      ],
    },
    {
      title: "Subscriptions, Billing, Free Trials, and Cancellations",
      paragraphs: [
        "Paid features may require a subscription. Billing is processed through in-app purchases and subscriptions via Apple App Store, Google Play Store, or other applicable app stores. Subscriptions may auto-renew unless canceled according to store rules.",
      ],
    },
    {
      title: "Voice Features",
      paragraphs: [
        "Voice features may receive user audio, convert it to text, and generate audio responses. This processing may be performed by ElevenLabs and Anthropic. For more details on processing, retention, and consent, see our Privacy Policy and in-app voice consent notice.",
      ],
    },
    {
      title: "Privacy and Data",
      paragraphs: [
        "Our Privacy Policy explains what information we collect, how we use it, what data may be sent to third-party AI providers, and how you can exercise your privacy rights.",
      ],
    },
    {
      title: "Third-Party Services",
      paragraphs: [
        "We use third-party providers including Anthropic, ElevenLabs, Firebase Analytics, app stores, payment processors, and infrastructure providers. Their handling of data is described in our Privacy Policy.",
      ],
    },
    {
      title: "Availability and Changes to the Service",
      paragraphs: [
        "We may modify, suspend, or discontinue features with reasonable notice where practicable.",
      ],
    },
    {
      title: "Intellectual Property",
      paragraphs: [
        `${siteConfig.name} content, branding, and software are owned by PAL or its licensors. You receive a limited, non-exclusive license to use the service for personal, non-commercial purposes.`,
      ],
    },
    {
      title: "Termination",
      paragraphs: [
        "We may suspend or terminate access for violations of these Terms or to protect users and the service. You may stop using the app at any time and delete your account in Settings.",
      ],
    },
    {
      title: "Disclaimers and Limitation of Liability",
      paragraphs: [
        'The service is provided "as is" and "as available" without warranties of any kind. To the maximum extent permitted by law, PAL shall not be liable for indirect, incidental, special, consequential, or punitive damages, or any loss arising from your use of or reliance on AI-generated content.',
      ],
    },
    {
      title: "Governing Law",
      paragraphs: [
        "These Terms are governed by the laws of the State of Georgia, United States, without regard to conflict-of-law principles.",
      ],
    },
    {
      title: "Changes to Terms",
      paragraphs: [
        'We may update these Terms. Material changes will be communicated in-app or by other reasonable means. Continued use after the effective date or updated "Last updated" date constitutes acceptance.',
      ],
    },
    {
      title: "Contact Information",
      paragraphs: [
        `Questions and support requests: ${siteConfig.supportEmail}. PAL, Georgia, United States.`,
      ],
    },
  ],
};

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  description:
    "How MindPAL collects, uses, shares, and protects your information, including what is sent to third-party AI services to generate responses.",
  sections: [
    {
      title: "Introduction",
      paragraphs: [
        `This Privacy Policy describes how PAL collects, uses, shares, and protects information when you use ${siteConfig.name}.`,
      ],
    },
    {
      title: "Information We Collect",
      paragraphs: [
        "We collect information you provide and information generated through your use of the app and website, as described below.",
      ],
    },
    {
      title: "Account Information",
      bullets: [
        "Email address and authentication identifiers.",
        "Profile, subscription status, and app entitlements.",
        "Account preferences, language, and support communications.",
      ],
    },
    {
      title: "Conversation, Journal, and User-Provided Content",
      paragraphs: [
        "We collect the text you enter, AI responses, journal-style reflections, check-ins, saved memories, uploaded or attached content where supported, and related metadata. This content may include sensitive personal information if you choose to provide it.",
      ],
    },
    {
      title: "Voice Data and Transcripts",
      paragraphs: [
        "If you use voice features, audio may be processed temporarily to convert speech to text and generate audio replies. We do not store raw audio recordings; voice input is processed in real time and deleted after processing. Transcripts and related context may be processed and stored according to this Privacy Policy.",
      ],
    },
    {
      title: "Mood, Wellbeing, Usage, Device, and Technical Data",
      bullets: [
        "Mood check-ins, feature usage, session metrics, and plan limit information.",
        "Device type, operating system version, app version, language, locale, crash logs, and performance logs.",
        "Purchase records and subscription status from app stores. We do not store full payment card numbers.",
      ],
    },
    {
      title: "How We Use Information",
      bullets: [
        "Provide, personalize, and improve emotional support, reflection, and voice features.",
        "Authenticate users, sync data where enabled, and enforce plan limits.",
        "Process AI and voice requests and generate AI responses.",
        "Maintain safety, detect abuse, troubleshoot issues, and comply with law.",
        "Communicate with you about the service, support, and important updates.",
      ],
    },
    {
      title: "Data Sent to Third-Party AI Services",
      paragraphs: [
        "MindPAL uses third-party AI services to process user messages and generate responses. For text features, the message or journal text you submit, relevant conversation context, AI safety signals, and technical request metadata may be sent to Anthropic to generate an AI response and operate the service.",
        "For voice features, audio may be sent to ElevenLabs for speech processing and voice output, and the resulting transcript and relevant context may be sent to Anthropic. We do not store raw audio recordings; voice input is processed in real time and deleted after processing.",
        "We use this processing only to provide MindPAL's AI conversation, reflection, safety, voice, and support features. We do not sell your personal information or use private conversations for advertising.",
      ],
    },
    {
      title: "How We Share Information",
      paragraphs: [
        "We share information with service providers who help us operate the app and website, including AI providers, voice providers, infrastructure providers, analytics providers, app stores, payment processors, and customer support tools. We may also disclose information when required by law, to protect rights and safety, or in connection with a business transfer.",
        "We do not sell your personal information and do not share private conversations for cross-context behavioral advertising.",
      ],
    },
    {
      title: "Data Retention and Deletion",
      paragraphs: [
        "We retain personal data for up to 365 days after your last activity with the service, or for as long as necessary to provide the service, comply with legal obligations, resolve disputes, and enforce our agreements. You may delete conversations and your account using in-app controls or by contacting support.",
      ],
    },
    {
      title: "Security",
      paragraphs: [
        "We use industry-standard safeguards. Data is encrypted in transit using TLS (HTTPS), and saved conversations and memories are encrypted at rest. No method of transmission or storage is completely secure, but we work to protect your data at every layer.",
      ],
    },
    {
      title: "International Data Transfers",
      paragraphs: [
        "Your information may be processed in countries other than your own, with appropriate safeguards where required.",
      ],
    },
    {
      title: "Children and Minors",
      paragraphs: [
        `${siteConfig.name} is not intended for children under 13 or the minimum age required in your region. We do not knowingly collect personal information from children without appropriate consent.`,
      ],
    },
    {
      title: "Your Rights",
      bullets: [
        "Access, correction, deletion, and portability where applicable.",
        "Withdraw consent for optional processing, including optional voice features.",
        "Object to or restrict certain processing where the law provides that right.",
        "Lodge a complaint with a supervisory authority where applicable.",
      ],
    },
    {
      title: "California / CCPA Notice",
      paragraphs: [
        "California residents may have additional rights regarding access, deletion, correction, opt-out of certain sharing, and limitation of sensitive personal information. We do not sell personal information or share it for cross-context behavioral advertising.",
      ],
    },
    {
      title: "GDPR Notice",
      paragraphs: [
        `EEA/UK users may contact ${siteConfig.supportEmail} for GDPR-related requests. Where applicable, we rely on contract performance, legitimate interests, consent, and legal obligations as our legal bases for processing.`,
      ],
    },
    {
      title: "Changes to Privacy Policy",
      paragraphs: [
        'We may update this Privacy Policy. The "Last updated" date will change and material updates will be communicated in-app or by other reasonable means where appropriate.',
      ],
    },
    {
      title: "Contact Information",
      paragraphs: [`Privacy and support requests: ${siteConfig.supportEmail}.`],
    },
  ],
};
